# Generated by Django 5.0.6 on 2024-06-04 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_macaddress_id_alter_macaddress_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macaddress',
            name='date_registered',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 15, 34, 20, 593922, tzinfo=datetime.timezone.utc)),
        ),
    ]
