# Generated by Django 5.0.6 on 2024-06-05 16:10

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_macaddress_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaddress',
            name='date_registered',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
